# Site settings
title: Fengjun Yang 杨逢君
# email: fyang3[attt]stanford[dottt]edu
# description: > # this means to ignore newlines until "baseurl:"
  # Welcome!
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fjyang.me" # the base hostname & protocol for your site
github_username:  FJYang96

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
